export type IconName =
  | 'nevel-tech-logo'
  | 'nevel-tech-logo-2'
  | 'toggle-menu'
  | 'arrow-right'
  | 'twitter'
  | 'youtube'
  | 'linkedin'
  | 'search'
  | 'home'
  | 'time-line'
  | 'all-game'
  | 'filter'
  | 'music'
  | 'poker';
